### PR TITLE
Install patch on Linuxes for patching snappy

### PR DESCRIPTION
**Pull request by jonkeane**

### CODE REVIEW

**Comment by jonkeane** [comment]
The macos errors are unrelated and fixed in #19

**Comment by nealrichardson** [comment]
I have a more meta concern about this. We got here because we wanted snappy on by default. But in order to have it on by default, it has to build successfully on CRAN, and that means it has to pass the sanitizer checks. To pass the sanitizer checks, we have to apply a patch. So now we can't install snappy if `patch` isn't available, so we've effectively added another dependency (not a burdensome one, but still). Is this the right tradeoff to make?

**Comment by jonkeane** [comment]
The extra patch dependency is temporary (when https://github.com/google/snappy/pull/148 is merged we can rip all of this out — I'm also eager to have clean sanitizer builds leading up to the Arrow release in case other code we depend on / write fails those checks, it's much easier to find and fix if we know it happens) 

In principle we could (and this is exactly what would happen, without the arrow r-package change) skip the patch step on platforms that don't have `patch` and build + use snappy just fine (albeit, with a sanitizer error). We disable snappy on platforms that don't have `patch` (in the r package) to ensure we don't accidentally find ourselves in a situation where an unpatched version of snappy gets to a CRAN sanitizer machine. 

I agree this is not great — though the benefit of having snappy on by default (cf https://issues.apache.org/jira/browse/ARROW-15047 just today) is high. Alternatively, we could patch and host the patched version of snappy ourselves and then we don't have to worry about if installing systems have `patch` which means we no longer have that extraneous dependency at build time.

**Comment by jonkeane** [comment]
Alternatively, we could take the r package bit out, and if the cran systems don’t have patch installed and this error ask for forgiveness + point to the fact we’ve sent upstream fixes?

**Comment by jonkeane** [comment]
And for clarity, when I'm talking about taking out the extra-paranoid r-arrow bit, I mean [deleting this](https://github.com/apache/arrow/blob/b1f009ca80ef6f12fbdf56a1b53ed8d0e0571a5a/r/inst/build_arrow_static.sh#L50-L54):

```
# Snappy 1.1.9 is patched to implement https://github.com/google/snappy/pull/148 but some platforms don't have
# patch available, so disable snappy in those cases. If the snappy version is bumped, we should remove this.
if [ ! $(command -v patch) ]; then
  ARROW_WITH_SNAPPY=OFF
fi
```

Which will allow arrow to be installed with snappy for all platforms (with or without `patch`), however platforms that _do not_ have `patch` will be subject to the address sanitizer issue

**Comment by nealrichardson** [comment]
We don't need this anymore right?

**Comment by jonkeane** [comment]
Correct, I should have and thought I had already closed it earlier!

**Pull request closed without merging**
